### PR TITLE
Feature embed all config assets and implement generator

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Implement a new `faasd generate` command that writes the default
  faasd configuration files to the local directory. The user can
  then customize the install by editing these files.
- Update the install command to copy the local configuration if it
  exists or fallback to the embedded configuration asset.
- Update the makefile to run the required `go generate` command to
  ensure the embedded assets are kept up to date

This implementation _should_ make the faasd more self-contained without 

## Motivation and Context

- [ ] I have raised an issue to propose this change **this is required**

Extends #76 , please _only_ look at the last commit

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by LucasRoesler** [comment]
@alexellis is this is pattern that you would be interested it? if not i can close the PR

**Comment by alexellis** [comment]
I have heard that Go 1.15 or 1.16 may ship this functionality in stdlib. Let's revisit it then and apply the same approach. Thank you for experimenting with this - something like `faas unpack` etc sounds like it would be useful for the installation.

We should consider how to go further and package containerd / runc and CNI in one download. @jsiebens may have ideas there.

**Comment by alexellis** [comment]
Here we are: https://tip.golang.org/pkg/embed/

**Comment by LucasRoesler** [comment]
@alexellis yeah, that needs us to update to 1.16 first, which comes out next month.

**Pull request closed without merging**
