### PR TITLE
Update faasd version in cloud-config.txt to 0.9.9

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @alexellis 

In relation to our conversation around #136:

I feel it might make sense to pull up the versions here. This way, new installs (like myself a week ago) won't get 0.9.5 anymore. I could also check the other dependencies, if you want.

I've tested this on a new VPS - works.

Maybe this could be switched to something automatic?

Cheers,
Peter

## Motivation and Context

- [ ] I have raised an issue to propose this change **this is required**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the PR, this was already been done yesterday, so I'll close it out.

**Comment by alexellis** [comment]
"I've tested this on a new VPS - works." <- as in fixes the content-type issue, or as in, the updated version didn't fail?

**Comment by spekulatius** [comment]
> "I've tested this on a new VPS - works." <- as in fixes the content-type issue, or as in, the updated version didn't fail?

That was only referring to the update. Not the content-type.



> Thanks for the PR, this was already been done yesterday, so I'll close it out.

Ah, okay. I didn't see that. Opened it yesterday and just came back to it.

**Comment by spekulatius** [comment]
I haven't used Go at all, so I think I can't be of much help in actually providing a fix.

**Pull request closed without merging**
