### PR TITLE
Provider returns secrets for a function

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description

This commit allows the provider to return a list of the names of the
secrets mapped into an openfaas function. This was tested by building
and deploying faasd on multipass and curling the provider directly and
seeing the returned secrets list!

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Motivation and Context

- [ ] I have raised an issue to propose this change **this is required**
Part of ongling work 

## How Has This Been Tested?

Unit tests for reading secrets from the mounts, then tested the provider - 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
Can you show us a quick curl | jq with the new input?

One with one secret, one with > 1 secret and one with no secrets.

**Comment by Waterdrips** [comment]
```
[
  {
    "name": "bar",
    "image": "docker.io/library/alpine:latest",
    "namespace": "openfaas-fn",
    "secrets": [
      "bar"
    ],
    "labels": {},
    "annotations": {}
  },
  {
    "name": "figlet",
    "image": "docker.io/functions/figlet:0.13.0",
    "namespace": "openfaas-fn",
    "labels": {},
    "annotations": {},
    "replicas": 1
  },
  {
    "name": "foo",
    "image": "docker.io/library/alpine:latest",
    "namespace": "openfaas-fn",
    "secrets": [
      "goo",
      "foo"
    ],
    "labels": {},
    "annotations": {}
  }
]

```

**Comment by Waterdrips** [comment]
Also for individual fns as well as the list

```sh
root@faasd:/home/ubuntu# curl http://admin:$OFPWD@localhost:8080/system/function/foo | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   104  100   104    0     0   1238      0 --:--:-- --:--:-- --:--:--  1238
{
  "name": "foo",
  "image": "",
  "namespace": "openfaas-fn",
  "secrets": [
    "goo",
    "foo"
  ],
  "labels": {},
  "annotations": {}
}
root@faasd:/home/ubuntu# curl http://admin:$OFPWD@localhost:8080/system/function/bar | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0   1152      0 --:--:-- --:--:-- --:--:--  1152
{
  "name": "bar",
  "image": "",
  "namespace": "openfaas-fn",
  "secrets": [
    "bar"
  ],
  "labels": {},
  "annotations": {}
}
root@faasd:/home/ubuntu# curl http://admin:$OFPWD@localhost:8080/system/function/figlet | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118  100   118    0     0   5363      0 --:--:-- --:--:-- --:--:--  5363
{
  "name": "figlet",
  "image": "",
  "namespace": "openfaas-fn",
  "labels": {},
  "annotations": {},
  "replicas": 1,
  "availableReplicas": 1
}
```

**Comment by alexellis** [comment]
LGTM

**Comment by alexellis** [comment]
/set title: Populate list of secrets in status endpoint

**Pull request merged**
