### PR TITLE
Removed auth plugin

### LINKED ISSUE #314: Remove basic auth plugin
Remove basic auth plugin

## Why do you need this?

In 0.26.0 of the gateway, we removed the basic auth plugin by building it directly into the gateway itself.

## Who is this for?

All faasd users.

## Current Behaviour

Uses the auth plugin

## Expected Behaviour

In the docker-compose.yaml file remove env-vars that set up the auth plugin for the gateway, then remove the auth plugin from the file.

Then, go through a basic test with deploying a function, checking the API still requires auth with curl and still allows auth to work for the protected endpoints like /system/functions.

### PR DESCRIPTION
**Pull request by nitishkumar71**
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>

## Description

Auth has been included in  gateway itself, so `auth-plugin` is not required.
## Motivation and Context

- [x] I have raised an issue to propose this change **this is required**
Closes #314 

## How Has This Been Tested?

1. Install using `hack/install.sh`
2. Login to faasd `sudo cat /var/lib/faasd/secrets/basic-auth-password | faas-cli login -s`
```
Calling the OpenFaaS server to validate the credentials...
credentials saved for admin http://127.0.0.1:8080
```
3. Deploy function `faas-cli deploy --image ghcr.io/openfaas/figlet:latest --name figlet`
```
Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/figlet
```
4. List functions `faas-cli ls`
```
Function                      	Invocations    	Replicas
figlet                        	0              	1    
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
Can you also try w/o auth to make sure that the new gateway image is doing what it's supposed to?

```
curl -i http://127.0.0.1:8080/system/functions
```

I'd also suggest opening the gateway URL in an incognito browser.

**Comment by alexellis** [comment]
@welteki perhaps you could fire up this config for a quick test? Only the compose file needs to change

**Comment by welteki** [comment]
> @welteki perhaps you could fire up this config for a quick test? Only the compose file needs to change

I will give this a quick test this evening.

**Comment by alexellis** [comment]
Thanks @welteki

**Comment by nitishkumar71** [comment]
Did some more test to be sure auth is working
1. send curl request `curl -i http://127.0.0.1:8080/system/functions`
```
HTTP/1.1 401 Unauthorized
Www-Authenticate: Basic realm="Restricted"
Date: Sat, 11 Feb 2023 17:42:49 GMT
Content-Length: 19
Content-Type: text/plain; charset=utf-8

invalid credentials
```

2. opened `http://127.0.0.1:8080/` in browser, got redirected to `http://127.0.0.1:8080/ui/`. Prompted for auth creds. Logged into system after providing creds and deployed function from store

**Comment by alexellis** [comment]
Looks good. Thank you

**Pull request merged**
