### PR TITLE
Bootstrap an AWS instance and pre-load it with a faasd instance

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

- Have re-organised the `/docs/bootstrap` directory to enable future bootstrapping scripts
  - I've moved the existing scripts into `digitalocean` and `digitalocean-nossl` and updated the main README.md.
- Updated the DO scripts to cater with Terraform v0.13.x. There was a breaking change how the dependency management works which broke these scripts with TF v0.13.
- Created an `aws` bootstrap script. Added docs

## Motivation and Context

- #103 I have raised an issue to propose this change **this is required**

## How Has This Been Tested?

Have installed and destroyed all three TF scripts with both TF 0.12.28 and 0.13.1 and they work as expected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MrSimonEmms** [comment]
Notes that I want people's thoughts on:
 - I'm not overly happy with the name I've used for the `digitalocean-nossl` script. Does anyone have any better ideas (also, open to improvements on the names for `aws` and `digitalocean`
- The `aws` script doesn't currently support SSL. It is my intention to add SSL support before final submission of this PR (just ran out of time tonight) unless there is a general "don't bother". If you're in that camp, please let me know and give reasons.

**Comment by alexellis** [comment]
Here's an idea, what do you think?

`digitalocean-nossl` + `digitalocean` merge, and `ssl` becomes an option, at if set in the terraform options, is used. If not set, it's not used.

**Comment by alexellis** [comment]
I would say that SSL w/ Caddy is what users will need for production usage of faasd.

Perhaps the AWS + DO recipes can both have Caddy as part of their setup, but make it optional as to whether it's installed?

**Comment by MrSimonEmms** [comment]
@alexellis yeah, that's a good shout. I did wonder about that, but wanted to run that through someone else before **CHANGING ALL THE THINGS**

I will be putting Caddy in AWS too and making that optional - that way, they can either run off "http://<ip_address>:8080" or "https://<subdomain>.<domain>"

**Comment by alexellis** [comment]
Do we want to create a bash script before or after this PR for #94? There have been no other volunteers yet and it should make the job simpler, you can even make Caddy part of the bash script.

**Comment by MrSimonEmms** [comment]
Yes, I think I'll have a go at #94 first. Even though it's not technically a dependency on this task, we should eat our own dogfood

**Comment by alexellis** [comment]
Good news, @jsiebens has completed #94 😄

**Comment by alexellis** [comment]
I think users could benefit from this. What can we do to help get this from draft to ready to merge? cc @jsiebens

**Comment by jsiebens** [comment]
I would be more in favour of creating Terraform Modules in separate repositories, which is the recommended approach (https://www.terraform.io/docs/modules/index.html#standard-module-structure). Doing so, we could even publish the modules in the Terraform Registry. If there is interest, I would be happy to help and contribute on such modules.

**Comment by alexellis** [comment]
Thanks for the suggestion @jsiebens - #131 has been merged now.

**Comment by alexellis** [comment]
This PR seems to have gone stale, I'll close it out, but would be open to a submission to the repo alongside the DigitalOcean sample/template.

**Pull request closed without merging**
