### PR TITLE
Add subdomain variable to terraform

### PR DESCRIPTION
**Pull request by MrSimonEmms**
Signed-off-by: Simon Emms <simon@simonemms.com>

## Motivation and Context

- [x] Raised to address #95 

## How Has This Been Tested?

Run against DO cluster

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
Please see also https://github.com/openfaas/faasd/issues/95#issuecomment-679041622

**Comment by MrSimonEmms** [comment]
@alexellis yeah, I'd seen the comment about adding a couple of tests but there aren't any in the TF stuff yet (that I can see at least). I've done a manual test with both those scenarios, but adding a test suite to the bootstrap seems outside the scope of this ticket

**Comment by alexellis** [comment]
A manual test to check that the change didn't break the existing behaviour, then another manual test (which I think you did?) to show the override works.

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
