### PR TITLE
Remove weave and netlink/netns library dependencies

### PR DESCRIPTION
**Pull request by carlosedp**
## Description

Provide a solution to fetch container IP addresses from CNI results
stored on the running node.

This removes external dependencies and clean-up the code.

This PR can be rebased after #28 is merged.

## Motivation and Context

- [x] I have raised an issue to propose this change **this is required**

Remove external dependencies and cleanup code. Solves issue #37.

## How Has This Been Tested?

Tested this PR with changes from PR from #28 successfully creating, deleting and calling functions.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
Please can you rebase this PR? After merging #28 it's not possible to review / checkout the diff.

**Comment by carlosedp** [comment]
Rebased on `master` after #28 merge.

**Comment by carlosedp** [comment]
Ping @alexellis. Rebased on master.

**Comment by carlosedp** [comment]
Evidences showing reboot allocates new IPs correctly after cleaning up the IP cache.

```
# Before reboot

❯ faas-cli store deploy figlet
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/figlet

❯ ll /var/run/cni/openfaas-cni-bridge/
total 36K
-rwxr-x--- 1 root root  0 Mar  8 10:06 lock*
-rw-r--r-- 1 root root 18 Mar  8 10:06 10.62.0.5
-rw-r--r-- 1 root root 23 Mar  8 10:06 10.62.0.6
-rw-r--r-- 1 root root 28 Mar  8 10:11 10.62.0.7
-rw-r--r-- 1 root root 15 Mar  8 10:11 10.62.0.8
-rw-r--r-- 1 root root 21 Mar  8 10:11 10.62.0.9
-rw-r--r-- 1 root root 18 Mar  8 10:11 10.62.0.10
-rw-r--r-- 1 root root 23 Mar  8 10:11 10.62.0.11
-rw-r--r-- 1 root root 10 Mar  8 10:11 last_reserved_ip.0
-rw-r--r-- 1 root root 17 Mar  8 10:11 10.62.0.12
❯ curl -d Test http://127.0.0.1:8080/function/figlet
 _____         _
|_   _|__  ___| |_
  | |/ _ \/ __| __|
  | |  __/\__ \ |_
  |_|\___||___/\__|

❯ cat /var/run/cni/openfaas-cni-bridge/10.62.0.12
figlet-3199
eth1%

❯ sc-status faasd-provider
● faasd-provider.service - faasd-provider
   Loaded: loaded (/lib/systemd/system/faasd-provider.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-08 10:11:02 EDT; 1min 16s ago
 Main PID: 2535 (faasd)
    Tasks: 8 (limit: 4700)
   Memory: 15.1M (limit: 500.0M)
   CGroup: /system.slice/faasd-provider.service
           └─2535 /usr/local/bin/faasd provider
❯ sc-status faasd
● faasd.service - faasd
   Loaded: loaded (/lib/systemd/system/faasd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-08 10:11:02 EDT; 1min 18s ago
 Main PID: 2526 (faasd)
    Tasks: 9 (limit: 4700)
   Memory: 14.5M (limit: 500.0M)
   CGroup: /system.slice/faasd.service
           └─2526 /usr/local/bin/faasd up


❯ sudo ctr -n openfaas-fn container ls
CONTAINER    IMAGE                                RUNTIME
figlet       docker.io/functions/figlet:0.13.0    io.containerd.runc.v2

❯ sudo ctr container ls
CONTAINER            IMAGE                                           RUNTIME
basic-auth-plugin    docker.io/openfaas/basic-auth-plugin:0.18.10    io.containerd.runc.v2
gateway              docker.io/openfaas/gateway:0.18.8               io.containerd.runc.v2
nats                 docker.io/library/nats-streaming:0.11.2         io.containerd.runc.v2
prometheus           docker.io/prom/prometheus:v2.14.0               io.containerd.runc.v2
queue-worker         docker.io/openfaas/queue-worker:0.9.0           io.containerd.runc.v2


❯ sudo reboot

----------------------------------------------------------------------------------------------
# After reboot, all services up automatically. New IPs allocated.

 sc-status faasd
● faasd.service - faasd
   Loaded: loaded (/lib/systemd/system/faasd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-08 10:18:39 EDT; 25s ago
 Main PID: 422 (faasd)
    Tasks: 9 (limit: 4700)
   Memory: 35.2M (limit: 500.0M)
   CGroup: /system.slice/faasd.service
           └─422 /usr/local/bin/faasd up
❯ sc-status faasd-provider
● faasd-provider.service - faasd-provider
   Loaded: loaded (/lib/systemd/system/faasd-provider.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-08 10:18:39 EDT; 26s ago
 Main PID: 415 (faasd)
    Tasks: 5 (limit: 4700)
   Memory: 15.3M (limit: 500.0M)
   CGroup: /system.slice/faasd-provider.service
           └─415 /usr/local/bin/faasd provider
❯ faas-cli ls
Function                      	Invocations    	Replicas
figlet                        	0              	0
❯ sudo ctr -n openfaas-fn container ls
CONTAINER    IMAGE                                RUNTIME
figlet       docker.io/functions/figlet:0.13.0    io.containerd.runc.v2
❯ sudo ctr container ls
CONTAINER            IMAGE                                           RUNTIME
basic-auth-plugin    docker.io/openfaas/basic-auth-plugin:0.18.10    io.containerd.runc.v2
gateway              docker.io/openfaas/gateway:0.18.8               io.containerd.runc.v2
nats                 docker.io/library/nats-streaming:0.11.2         io.containerd.runc.v2
prometheus           docker.io/prom/prometheus:v2.14.0               io.containerd.runc.v2
queue-worker         docker.io/openfaas/queue-worker:0.9.0           io.containerd.runc.v2
❯ ls /var/run/cni/openfaas-cni-bridge
10.62.0.2  10.62.0.3  10.62.0.4  10.62.0.5  10.62.0.6  last_reserved_ip.0  lock*
❯
❯ curl -d Test http://127.0.0.1:8080/function/figlet
Can't reach service for: figlet.
❯ curl -d Test http://127.0.0.1:8080/function/figlet
 _____         _
|_   _|__  ___| |_
  | |/ _ \/ __| __|
  | |  __/\__ \ |_
  |_|\___||___/\__|

```

**Comment by alexellis** [comment]
Thank you for the rebase, which means I can put this back onto my list. 👍

**Comment by carlosedp** [comment]
I'm looking into an alternative way to do it... looking at the IP allocations. Give me some minutes. I'll let you know.

**Comment by alexellis** [comment]
@martindekov would you have time to run through some exploratory testing of the PR? I.e. try to break it, try the common usecases

**Comment by carlosedp** [comment]
Now it's good to go. I've changed the `GetIPAddress` so it fetches from IP allocation dir `/var/run/cni` instead of the results dir.

**Comment by alexellis** [comment]
I think we have this now, but from another PR? Can you confirm if I'm remembering correctly or whether this needs to be rebased and considered again for merged?

**Comment by carlosedp** [comment]
Hey, I need to take a look again. It's been a long time ago...

**Comment by alexellis** [comment]
Thanks @carlosedp - I think this would increase performance on RPi3 which would be helpful for the community, plus it should be felt during load tests and higher traffic for regular use on cloud.

**Comment by alexellis** [comment]
Updated, unit-tested and documented in #165

Thanks for the PR @carlosedp

**Pull request closed without merging**
